routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/companies','CompanyController');
Route::resource('/employees','EmployeeController');

app/Company.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    //
    protected $fillable = ['name', 'email', 'website', 'logo'];
}

app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    protected $fillable = ['company_id','first_name','last_name', 'email', 'phone'];

    public function company()
    {
        return $this->belongsTo('App\Company');
    }

    public function getNameAttribute()
    {
        return $this->first_name.' '.$this->last_name;
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Company;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;
use App\Http\Requests\CompanyStoreRequest;
use App\Http\Requests\CompanyUpdateRequest;
use League\CommonMark\Inline\Element\Image;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $companies = Company::paginate(10);
        return view('company.index')->with(['companies'=>$companies]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('company.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CompanyStoreRequest $request)
    {
        if ($request->hasFile('logo')) {
            $image      = $request->file('logo');
            $fileName   = time() . '.' . $image->getClientOriginalExtension();
            Storage::disk('public')->put($fileName, File::get($image), 'public');
        }else{
            $fileName = '';
        }

        $data = $request->except('_token');
        $data['logo'] = $fileName;

        Company::create($data);

        return redirect()->route('companies.index')->with('status','Company Created Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function show(Company $company)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function edit(Company $company)
    {
        return view('company.edit')->with(['company'=>$company]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function update(CompanyUpdateRequest $request, Company $company)
    {
        if ($request->hasFile('logo')) {
            $image      = $request->file('logo');
            $fileName   = time() . '.' . $image->getClientOriginalExtension();
            Storage::disk('public')->put($fileName, File::get($image), 'public');
        }else{
            $fileName = $company->logo;
        }

        $data = $request->except('_token');
        $data['logo'] = $fileName;

        Company::find($company->id)->update($data);

        return redirect()->route('companies.index')->with('status','Company Updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function destroy(Company $company)
    {
        Company::whereId($company->id)->delete();
        return redirect()->route('companies.index')->with('status','Company Deleted Successfully');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Company;
use App\Employee;
use Illuminate\Http\Request;
use App\Http\Requests\EmployeeStoreRequest;
use App\Http\Requests\EmployeeUpdateRequest;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $employees = Employee::with('company')->paginate(10);
        return view('employee.index')->with(['employees'=>$employees]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $companies = Company::select('id','name')->get();
        return view('employee.add')->with(['companies'=>$companies]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(EmployeeStoreRequest $request)
    {
        $data = $request->except('_token');

        Employee::create($data);

        return redirect()->route('employees.index')->with('status','Employee Created Successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function show(Employee $employee)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function edit(Employee $employee)
    {
        $companies = Company::select('id','name')->get();
        return view('employee.edit')->with(['employee'=>$employee, 'companies' => $companies]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function update(EmployeeUpdateRequest $request, Employee $employee)
    {
        $data = $request->except('_token','_method');

        Employee::whereId($employee->id)->update($data);

        return redirect()->route('employees.index')->with('status','Employee Updated Successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function destroy(Employee $employee)
    {
        Employee::whereId($employee->id)->delete();

        return redirect()->route('employees.index')->with('status','Employee Deleted Successfully.');
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/company/add.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <a class="btn btn-primary" href="{{route('home')}}">Back</a>
                    {{ __('Create New Company') }}
                </div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @elseif (session('error'))
                        <div class="alert alert-danger" role="alert">
                            {{ session('error') }}
                        </div>
                    @elseif (count($errors) > 0)
                        <div class="alert alert-danger" role="alert">
                            {{ $errors->first() }}
                        </div>
                    @endif

                    <div class="row">
                        <div class="col">
                            <form method="post" action="{{route('companies.store')}}" enctype='multipart/form-data' >
                            @csrf
                                {{-- Name   --}}
                                <div class="form-group">
                                    <label>Name</label>
                                    <input type="text" name="name" class="form-control" value="{{old('name')}}" required>
                                    @if($errors->has('name'))
                                    <span class="errorfield">
                                        <i class="fa fa-exclamation-circle" aria-hidden="true"></i> {{ $errors->first('name')}}
                                    </span>
                                    @endif
                                </div>
                                {{--  Email  --}}
                                <div class="form-group">
                                    <label>Email</label>
                                    <input type="email" name="email" class="form-control" value="{{old('email')}}" required>
                                    @if($errors->has('email'))
                                    <span class="errorfield">
                                        <i class="fa fa-exclamation-circle" aria-hidden="true"></i> {{ $errors->first('email')}}
                                    </span>
                                    @endif
                                </div>
                                <div class="form-group">
                                    <label>Website</label>
                                    <input type="text" name="website" class="form-control" value="{{old('website')}}" required >
                                    @if($errors->has('website'))
                                    <span class="errorfield">
                                        <i class="fa fa-exclamation-circle" aria-hidden="true"></i> {{ $errors->first('website')}}
                                    </span>
                                    @endif
                                </div>
                                <div class="form-group">
                                    <label>LOGO</label>
                                    <input type="file" name="logo" class="form-control" value="{{old('logo')}}" required >
                                    @if($errors->has('logo'))
                                    <span class="errorfield">
                                        <i class="fa fa-exclamation-circle" aria-hidden="true"></i> {{ $errors->first('logo')}}
                                    </span>
                                    @endif
                                </div>
                                
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/company/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <a class="btn btn-primary" href="{{route('companies.index')}}">Back</a>
                    {{ __('Edit Company') }}
                </div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @elseif (session('error'))
                        <div class="alert alert-danger" role="alert">
                            {{ session('error') }}
                        </div>
                    @elseif (count($errors) > 0)
                        <div class="alert alert-danger" role="alert">
                            {{ $errors->first() }}
                        </div>
                    @endif

                    <div class="row">
                        <div class="col">
                            <form method="post" action="{{route('companies.update',['company' => $company->id])}}" enctype='multipart/form-data' >
                            @csrf
                            <input type="hidden" name="_method" value="PUT">
                                {{-- Name   --}}
                                <div class="form-group">
                                    <label>Name</label>
                                    <input type="text" name="name" class="form-control" value="{{old('name') ? old('name') : $company->name}}" required>
                                    @if($errors->has('name'))
                                    <span class="errorfield">
                                        <i class="fa fa-exclamation-circle" aria-hidden="true"></i> {{ $errors->first('name')}}
                                    </span>
                                    @endif
                                </div>
                                {{--  Email  --}}
                                <div class="form-group">
                                    <label>Email</label>
                                    <input type="email" name="email" class="form-control" value="{{old('email') ? old('email') : $company->email}}" required>
                                    @if($errors->has('email'))
                                    <span class="errorfield">
                                        <i class="fa fa-exclamation-circle" aria-hidden="true"></i> {{ $errors->first('email')}}
                                    </span>
                                    @endif
                                </div>
                                <div class="form-group">
                                    <label>Website</label>
                                    <input type="text" name="website" class="form-control" value="{{old('website') ? old('website') : $company->website}}" required >
                                    @if($errors->has('website'))
                                    <span class="errorfield">
                                        <i class="fa fa-exclamation-circle" aria-hidden="true"></i> {{ $errors->first('website')}}
                                    </span>
                                    @endif
                                </div>
                                <div class="form-group">
                                    <label>LOGO</label>
                                    <img src="{{asset($company->logo)}}" alt="{{$company->name}}" height="100" width="100">
                                    <input type="file" name="logo" class="form-control" value="{{old('logo')}}" >
                                    @if($errors->has('logo'))
                                    <span class="errorfield">
                                        <i class="fa fa-exclamation-circle" aria-hidden="true"></i> {{ $errors->first('logo')}}
                                    </span>
                                    @endif
                                </div>
                                
                                <button type="submit" class="btn btn-primary">Update</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/company/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <a class="btn btn-primary" href="{{route('home')}}">Back</a>
                    {{ __('Companies') }}
                </div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @elseif (session('error'))
                        <div class="alert alert-danger" role="alert">
                            {{ session('error') }}
                        </div>
                    @endif
                    <a class="btn btn-success mb-2 text-white" href="{{route('companies.create')}}">Create new Company</a>
                    <br>
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">Logo</th>
                                <th scope="col">Name</th>
                                <th scope="col">Email</th>
                                <th scope="col">Website</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                                @forelse($companies as $company)
                                <tr>
                                    <td scope="col">
                                        <img src="{{asset($company->logo)}}" height='100' width='100' alt="{{$company->name}}">
                                    </td>
                                    <td scope="col">{{$company->name}}</td>
                                    <td scope="col">{{$company->email}}</td>
                                    <td scope="col">{{$company->website}}</td>
                                    <td scope="col">
                                        <a class="btn btn-sm" href="{{route('companies.edit',['company' => $company->id])}}">Edit</a>
                                        <form action="{{route('companies.destroy',['company' => $company->id])}}" method="post">
                                        @method('DELETE')
                                        @csrf
                                        <button class="btn btn-sm btn-danger">Delete</button>
                                        </form> 
                                    </td>
                                </tr>
                                @empty
                                <tr>
                                    <td colspan="5"> No Company Found</td>
                                </tr>
                                @endforelse
                        </tbody>
                    </table>

                    {{$companies->links()}}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/employee/add.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <a class="btn btn-primary" href="{{route('employees.index')}}">Back</a>
                    {{ __('Add New Employee') }}
                </div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @elseif (session('error'))
                        <div class="alert alert-danger" role="alert">
                            {{ session('error') }}
                        </div>
                    @elseif (count($errors) > 0)
                        <div class="alert alert-danger" role="alert">
                            {{ $errors->first() }}
                        </div>
                    @endif

                    <div class="row">
                        <div class="col">
                            <form method="post" action="{{route('employees.store')}}" >
                            @csrf
                                {{-- Company   --}}
                                <div class="form-group">
                                    <label>Company</label>
                                    <select class="form-control" required name="company_id">
                                        <option value="" disabeld selected>Please Select Company</option>
                                        @foreach($companies as $company)
                                            <option value="{{$company->id}}" {{old('company_id') == $company->id ? 'selected' : ''}}>{{$company->name}}</option>
                                        @endforeach
                                    </select>
                                    @if($errors->has('company_id'))
                                    <span class="errorfield">
                                        <i class="fa fa-exclamation-circle" aria-hidden="true"></i> {{ $errors->first('company_id')}}
                                    </span>
                                    @endif
                                </div>
                                {{-- Name   --}}
                                <div class="form-group">
                                    <label>First Name</label>
                                    <input type="text" name="first_name" class="form-control" value="{{old('first_name')}}" required>
                                    @if($errors->has('first_name'))
                                    <span class="errorfield">
                                        <i class="fa fa-exclamation-circle" aria-hidden="true"></i> {{ $errors->first('first_name')}}
                                    </span>
                                    @endif
                                </div>
                                <div class="form-group">
                                    <label>Last Name</label>
                                    <input type="text" name="last_name" class="form-control" value="{{old('last_name')}}" required>
                                    @if($errors->has('last_name'))
                                    <span class="errorfield">
                                        <i class="fa fa-exclamation-circle" aria-hidden="true"></i> {{ $errors->first('last_name')}}
                                    </span>
                                    @endif
                                </div>
                                {{--  Email  --}}
                                <div class="form-group">
                                    <label>Email</label>
                                    <input type="email" name="email" class="form-control" value="{{old('email')}}" required>
                                    @if($errors->has('email'))
                                    <span class="errorfield">
                                        <i class="fa fa-exclamation-circle" aria-hidden="true"></i> {{ $errors->first('email')}}
                                    </span>
                                    @endif
                                </div>
                                <div class="form-group">
                                    <label>Phone</label>
                                    <input type="number" name="phone" class="form-control" value="{{old('phone')}}" required >
                                    @if($errors->has('phone'))
                                    <span class="errorfield">
                                        <i class="fa fa-exclamation-circle" aria-hidden="true"></i> {{ $errors->first('phone')}}
                                    </span>
                                    @endif
                                </div>
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/employee/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <a class="btn btn-primary" href="{{route('home')}}">Back</a>
                    {{ __('Employees') }}
                </div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @elseif (session('error'))
                        <div class="alert alert-danger" role="alert">
                            {{ session('error') }}
                        </div>
                    @endif
                    <a class="btn btn-success mb-2 text-white" href="{{route('employees.create')}}">Add Employee</a>
                    <br>
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">Company</th>
                                <th scope="col">Name</th>
                                <th scope="col">Email</th>
                                <th scope="col">Phone</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                                @forelse($employees as $employee)
                                <tr>
                                    <td scope="col">
                                        {{$employee->company->name}}
                                    </td>
                                    <td scope="col">{{$employee->name}}</td>
                                    <td scope="col">{{$employee->email}}</td>
                                    <td scope="col">{{$employee->phone}}</td>
                                    <td scope="col">
                                        <a class="btn btn-sm" href="{{route('employees.edit',['employee' => $employee->id])}}">Edit</a>
                                        <form action="{{route('employees.destroy',['employee' => $employee->id])}}" method="post">
                                        @method('DELETE')
                                        @csrf
                                        <button class="btn btn-sm btn-danger">Delete</button>
                                        </form> 
                                    </td>
                                </tr>
                                @empty
                                <tr>
                                    <td colspan="5"> No Employee Found</td>
                                </tr>
                                @endforelse
                        </tbody>
                    </table>

                    {{$employees->links()}}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    {{ __('Dashboard') }}
                    <a class="btn btn-primary" href="{{route('companies.index')}}">Companies</a>
                    <a class="btn btn-primary" href="{{route('employees.index')}}">Employees</a>
                </div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('Welcome Admin To Mini CRM') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection